CatAdoption/Models/Cat.cs
namespace CatAdoption.Models
{
    public class Cat
    {
        public int CatId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string Bio { get; set; }
        public string ImagePath { get; set; }
    }
}

CatAdoption/Models/ViewModels/AddCatViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CatAdoption.Models
{
    public class AddCatViewModel
    {
        public string Name { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string Bio { get; set; }
        public IFormFile Image { get; set; }
        public SelectList Genders { get; set; }

    }
}

CatAdoption/Controllers/CatController.cs
using CatAdoption.Data;
using CatAdoption.Models;
using CatAdoption.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CatAdoption.Controllers
{
    public class CatController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly CatDbContext _catContext;
        private readonly IWebHostEnvironment _hostingEnvironment;
        ICatRepository _catRepo;
        IAdoptRepository _adoptRepo;

        public CatController(ICatRepository catRepo, IAdoptRepository adoptRepo, UserManager<IdentityUser> userManager, CatDbContext catContext, IWebHostEnvironment hostingEnvironment)
        {
            _catRepo = catRepo;
            _userManager = userManager;
            _adoptRepo = adoptRepo;
            _catContext = catContext;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index(string catGender, int catAge)
        {
            IQueryable<string> genderQuery = from g in _catContext.Cats
                                             orderby g.Gender
                                             select g.Gender;

            var cats = from g in _catContext.Cats
                       select g;

            IQueryable<int> ageQuery = from a in _catContext.Cats
                                       orderby a.Age
                                       select a.Age;

            var ageCats = from a in _catContext.Cats
                          select a;

            if (catAge != 0 && (!string.IsNullOrEmpty(catGender)))
            {
                cats = cats.Where(x => x.Age == catAge && x.Gender == catGender);
            }
            else if (!string.IsNullOrEmpty(catGender))
            {
                cats = cats.Where(x => x.Gender == catGender);
            }
            else if (catAge != 0)
            {
                cats = cats.Where(x => x.Age == catAge);
            }

            var catFilterVM = new CatFilterViewModel
            {
                Genders = new SelectList(await genderQuery.Distinct().ToListAsync()),
                Ages = new SelectList(await ageQuery.Distinct().ToListAsync()),
                Cats = await cats.ToListAsync()
            };

            return View(catFilterVM);
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            var model = _catRepo.GetById(id);
            return View(model);
        }

        [HttpGet("cat/adopt")]
        [Authorize]
        public IActionResult Adopt(int id)
        {
            var model = _catRepo.GetById(id);
            return View(model);
        }

        [HttpGet("cat/adopt/success/{id}")]
        [Authorize]
        public async Task<IActionResult> AdoptSuccessAsync(int id)
        {
            var cat = _catRepo.GetById(id);
            var userId = await _userManager.GetUserAsync(HttpContext.User);
            _adoptRepo.Adopt(cat, userId.ToString());
            return RedirectToAction("Index");
        }

        [HttpGet("cat/adoptedcats")]
        [Authorize]
        public IActionResult AdoptedCats()
        {
            var model = _adoptRepo.GetAll();
            return View(model);
        }

        [HttpGet("cat/mycats")]
        [Authorize]
        public async Task<IActionResult> MyCatsAsync()
        {
            var userId = await _userManager.GetUserAsync(HttpContext.User);
            var currentUser = userId.ToString();
            var usersCats = _adoptRepo.GetAll()
                   .Where(usersCats => usersCats.UserId == currentUser);
            return View(usersCats);
        }

        [HttpGet]
        [Authorize]
        public IActionResult AddCat()
        {
            var addCatVM = new AddCatViewModel();
            return View(addCatVM);
        }        

        [HttpPost]
        [Authorize]
        public IActionResult AddCat(AddCatViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if(model.Image != null)
                {
                    string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "imgs");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Image.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.Image.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                Cat newCat = new Cat
                {
                    Name = model.Name,
                    Age = model.Age,
                    Gender = model.Gender,
                    Bio = model.Bio,
                    ImagePath = uniqueFileName
                };
                _catRepo.AddCat(newCat);
                return RedirectToAction("Details", new { id = newCat.CatId });
            }
            return View();
        }
    }
}

CatAdoption/Views/Cat/AddCat.cshtml
@model AddCatViewModel

@{
    ViewData["Title"] = "AddCat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>New Adoption</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCat" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender">
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label    >
                <div class="custom-file">
                    <input asp-for="Image" class="form-control custom-file-input" />
                    <label class="custom-file-label">Choose File...</label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Cat" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-success">Back to list</a>
            </div>

            <div asp-validation-summary="All" class="text-danger"></div>

            @section Scripts {
            <script>
                $(document).ready(function () {
                    $('.custom-file-input').on("change", function () {
                        var fileName = $(this).val().split("\\").pop();
                        $(this).next('.custom-file-label').html(fileName);
                    });
                })  
            </script>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CatAdoption/Views/Cat/Adopt.cshtml
@model CatAdoption.Models.Cat

@{
    ViewData["Title"] = "Adopt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="text-center">Would you like to adopt @Model.Name?</h3>

<div class="text-center">
    <img src="~/imgs/@Model.ImagePath" class="img-thumbnail col-lg-6"/>
    <h5>@Model.Gender</h5>
    <h5>Age: @Model.Age</h5>
    <p>@Model.Bio</p>
    <a class="btn btn-primary" asp-action="AdoptSuccess" asp-route-id="@Model.CatId">Adopt</a>
    <br />
    <a asp-action="Index">Back to List</a>
</div>

CatAdoption/Views/Cat/AdoptedCats.cshtml
@model IEnumerable<CatAdoption.Models.Adoption>

@{
    ViewData["Title"] = "AdoptedCats";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Cats who found a new home!</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bio)
            </td>
        </tr>
}
    </tbody>
</table>

CatAdoption/Views/Cat/Details.cshtml
@model CatAdoption.Models.Cat

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Successfully added @Model.Name to the database!</h3>

<div class="text-center">
    <img src="~/imgs/@Model.ImagePath" class="img-thumbnail col-lg-6" />
    <h5>@Model.Gender</h5>
    <h5>Age: @Model.Age</h5>
    <p>@Model.Bio</p>
    <a asp-action="Index">Back to List</a>
</div>

CatAdoption/Views/Cat/Index.cshtml
@model CatAdoption.Models.CatFilterViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>These fine felines need a home!</h1>
<hr />

<form asp-controller="Cat" asp-action="Index" method="get">
    <p>

        Gender: <select asp-for="CatGender" asp-items="Model.Genders">
            <option value="">All</option>
        </select>

        Age: <select asp-for="CatAge" asp-items="Model.Ages">
            <option value="">All</option>
        </select>

        <input type="submit" value="Filter" />

    </p>
</form>

<div class="d-flex flex-wrap">
    @foreach (var item in Model.Cats)
    {
        <div class="card col-12 col-md-6 col-lg-3 text-center">
            <img src="~/imgs/@item.ImagePath" class="card-img-top rounded pt-2" alt="@item.Name">
            <div class="card-body justify-content-center">
                <h5 class="card-title">@item.Name</h5>
                <p class="card-text">@item.Gender</p>
                <p class="card-text">Age: @item.Age</p>
                <p class="card-text">@item.Bio</p>
                <a class="btn btn-primary" asp-action="adopt" asp-route-id="@item.CatId">Adopt</a>
            </div>
        </div>
    }
</div>

CatAdoption/Views/Cat/MyCats.cshtml
@model IEnumerable<CatAdoption.Models.Adoption>

@{
    ViewData["Title"] = "MyCats";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>My Cats</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bio)
            </td>
        </tr>
}
    </tbody>
</table>